### ISSUE TITLE
How can we add support for G15 5530?

### ISSUE THREAD

**Issue by tr1xem** [Mohit-Pala/Dell_G15_Fan_Cli#3]
Is there any way we can do that?

**Comment by Mohit-Pala** [comment]
I see 5530 uses Intel, I don't have that model to try out


Could you try downloading the Python file and find and replace the
following

Find -> AMW3

Replace with -> AMWW

This works on other Intel models

**Comment by tr1xem** [comment]
Can confirm this works

**Comment by tr1xem** [comment]
Is there any way to check the laptop model through acpi call?

**Comment by Mohit-Pala** [comment]
Sorry, im not sure how we can achieve that, i found the acpi commands in arch wiki (https://wiki.archlinux.org/title/Dell_G15_5525) and from this repo https://github.com/cemkaya-mpi/Dell-G15-Controller

**Comment by tr1xem** [comment]
Oh Thanks for the reference

**Comment by tr1xem** [comment]
Added Support for G15 5530
